### PR TITLE
Respect yvm legacy .yvmrc

### PR DESCRIPTION
**Pull request by chadmetcalf-cb**
Respects yvm's legacy .ymvrc file

### CODE REVIEW

**Comment by chadmetcalf-cb** [comment]
@canterberry This has been tested with `asdf plugin test yarn https://github.com/metcalf-clearbit/asdf-yarn.git`. Are there any other checks that you would like to see?

**Comment by chadmetcalf-cb** [comment]
An additional feature for the future could be to respect `.yarnrc` binary path, if provided.

**Comment by canterberry** [comment]
Thanks @metcalf-clearbit for this. I don't see any issue with merging this; ~~could you provide some additional context in the PR description to help future readers (including myself!) better understand the problem this changeset aims to solve?~~
**Edit:** References added in a follow-up comment below. This is for a smoother transition from [yvm](https://yvm.js.org/) to asdf.

**Review by canterberry — APPROVED** [review]
LGTM.
References:
 * https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md#binlist-legacy-filenames
 * https://yvm.js.org/docs/overview#configuration-file

**Pull request merged**
