### PR TITLE
enable customization of GNUPGHOME

### PR DESCRIPTION
**Pull request by ezracelli**

### CODE REVIEW

**Comment by canterberry** [comment]
Hi @ezracelli , thanks for the PR!

I appreciate the context you've added to the README for this -- it clarifies the problem you were running into and why you chose to solve it this way. :+1:

To make sure I understand correctly: if the path described by `ASDF_DIR` is not a writable directory, then `asdf install yarn ...` fails because it cannot create the `${ASDF_DIR}/keyrings/yarn` directory it needs to hold its GPG keyring.

Your solution is a bit heavy-handed, though: if the user has `GNUPGHOME` set in their environment for any other reason, then this plugin would pollute that keyring instead (and trust any keys in that keyring, too!).

I'd like to take a step back and ponder alternative solutions that could solve your issue without potentially causing other issues or leaking implementation details:

 1. Update this plugin to create a temporary keyring (i.e: using `mktemp -d`) instead of a permanent one, and delete that keyring after use. This should solve your issue and improve upon the current implementation overall by removing an unnecessarily persistent keyring.
 2. Create a PR in the asdf-vm/asdf repo to initialize a `${ASDF_DIR}/keyrings` directory and ensure this directory is user-owned and user-writable after sourcing. This establishes a pattern for other plugins to follow when a plugin-managed GPG keyring is needed without having write access to the entire `ASDF_DIR` directory.
 3. ...other ideas?

Again, thanks for your work! Let's figure out a way to solve this for you and others who share the same problem.

**Comment by ezracelli** [comment]
@canterberry Yeah, those are great points, it is a bit heavy-handed. You're exactly right about the problem I was trying to solve btw!

I took inspiration from the [asdf-nodejs](https://github.com/asdf-vm/asdf-nodejs) for the customization of `GNUPGHOME` in their ["Using a dedicated OpenPGP keyring"](https://github.com/asdf-vm/asdf-nodejs#using-a-dedicated-openpgp-keyring) step. However, I think the solution there is a bit different. Since downloading the keys is an explicit step rather than being included in `asdf install ...`, it's more obvious to the user that that `GNUPGHOME` variable is coming into play.

[`asdf`'s documentation](https://asdf-vm.com/#/core-configuration?id=environment-variables) lists another environment variable `ASDF_DATA_DIR` (defaulting to `~/.asdf`) &mdash; maybe a better place to put the keyring would be `${ASDF_DATA_DIR:-$HOME/.asdf}/keyrings/yarn`?

**Comment by canterberry** [comment]
Ah, `ASDF_DATA_DIR` sounds like exactly what we need here. It looks like `ASDF_DATA_DIR` is *not* defined by default, but from local experimentation I can see that it does indeed affect where `asdf` looks for plugins, et al.

`ASDF_DIR`, by default, points at the directory where asdf is installed. However, local experimentation confirms that regardless of install location, asdf does install plugins to `~/.asdf`, so `ASDF_DATA_DIR` does effectively default to `~/.asdf`.

Your proposed path of `${ASDF_DATA_DIR:-$HOME/.asdf}/keyrings/yarn` sounds exactly right.

**Comment by ezracelli** [comment]
@canterberry 100% forgot about this, sorry!! Should be good to go now.

**Review by canterberry — APPROVED** [review]
:+1: LGTM! Minimal and spot-on.

**Pull request merged**
